analytics: {}
color:
  brandColors:
    - '#030303'
    - '#f8f8f8'
    - '#9a9ac8'
    - '#8c4b8c'
    - '#ff8bd9'
  brandStrength: 0
  lightness: 0.527052
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.78857
name: guided hallucination
opengraph: {}
purpose:
  - name: engagement
    item: ad31ef10-e553-45a8-a720-a0871504ea81
typography_spectrum: 0.0686
