name: guided hallucination
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#f8f8f8'
    - '#9a9ac8'
    - '#8c4b8c'
    - '#ff8bd9'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: null
    url: null
